### ISSUE TITLE
No way to set pager height depending on children height or, that children would be on the bottom

### ISSUE THREAD

**Issue by ramunasjurgilas** [fermoya/SwiftUIPager#11]
I need that pager children would be located at the bottom of the screen. It is possible to do it in two ways:
1. Change pager height deepening on child height.
2. Make, that children will alway be attached to the bottom of the screen.

**_How to make that children will be attached to the bottom?_** 

I did not manage to do it using **Spacer**, **ZStack**, **VStack** and other ways. In the screenshot presented what I am getting using this code:

```
    var body: some View {
        VStack {
            Spacer()
                .frame(height: 400)
            Pager(page: $pageIndex, data: items) { _ in
                HStack {
                    Spacer()
                MyCellView(model: self.items[self.pageIndex])
                }
            }
            .itemSpacing(10)
            .padding(8)
            .itemAspectRatio(0.9)
            .background(Color.red)
        }
    }
```

<img width="423" alt="Screenshot 2020-02-24 at 15 07 21" src="https://user-images.githubusercontent.com/255732/75155310-73b08000-5718-11ea-94f4-337b9a7ff207.png">

**Comment by fermoya** [comment]
Hi @ramunasjurgilas ,

I know what you mean, thank for your input. Right now I don't have a way to do this, I'll add it as part of a new release, I'll keep you posted.

At the moment, I think there might be something you can do, though. I think if you change `MyCellView` and include a new `VStack` to push your cell to the bottom, you could achieve what you want. Remove `itemAspectRatio` so that it takes up all the available space.

I'll let you know when I add a way to position the cell.

Fernando

**Comment by fermoya** [comment]
Hi,

You can use `itemAspectRatio` inn version 1.3.0 to pass an alignment to the page.

Note that `start` will set the page at the top, if horizontal, and left, if vertical. `end` will do the opposite.

Let me know if this works for you.

Fernando

**Comment by ramunasjurgilas** [comment]
Thanks @fermoya for very quick support! Now I have what I want!
