### ISSUE TITLE
[BUG] explicit animations inside the pager don't seem to work

### ISSUE THREAD

**Issue by vanities** [fermoya/SwiftUIPager#128]
**Describe the bug**
Adding an animation inside the pager seems to not work without adding an `.animation(.default)`

**To Reproduce**
```
import SwiftUI
import SwiftUIPager

struct TestPager: View {
    @State var currentPage: Int = 0
    @State var buttonText: String = "hsduahsd"
    
    var body: some View {
        Pager(page: $currentPage, data: Array(0..<4), id: \.self, content: { _ in
            Button(action: { withAnimation(.linear(duration: 5)) {
                self.buttonText = "asdasdads"
            }}, label: {
                Text(buttonText)
            })
        })
    }
}
```

**Expected behavior**
The above code runs and animates for 5 seconds

**Environment:**
 - OSX: 11 Beta MacOS / iOS 14
 - Device: iPhone11
- SwiftUIPager version: 1.11.0

Thanks for your time!

**Comment by vanities** [comment]
For reference, I did see https://github.com/fermoya/SwiftUIPager/issues/82

**Comment by fermoya** [comment]
Hi @vanities , I have an `animation(nil)` in the implementation so that a property (opacity) doesn’t get animated. This seems to be causing the page not to get animated unless specified implicitly.
```
pageContent // your page implementation
    // inside Pager library 
    .modifier1
    .modifier2
    .animation(nil) // to prevent modifier1 and modifier2 from getting animated
     .modifier3
```
This seems to be affecting the pagerContent. Do you know any other way to disable the animation of a modifier?

I’ll take a look and see what I can do but for now you’ll have to use implicit animations
```
.animation(.linear(duration: 5))
```

**Comment by vanities** [comment]
I'm not actually sure.. I do know that you could add another `.animation()` after the modifier you want disabled (after `.modifier3`, and that may fix it. Although, I'm not sure what should go in there.. maybe `.animation(.default)`?

Thanks for the quick response!

**Comment by vanities** [comment]
Hmm actually, I just tried that and it didn't seem to work.

**Comment by fermoya** [comment]
This code works:
```

import SwiftUI
import SwiftUIPager

struct TestPager: View {
    @State var currentPage: Int = 0
    @State var buttonText: String = "hsduahsd"
    
    var body: some View {
        Pager(page: $currentPage, data: Array(0..<4), id: \.self, content: { _ in
            Button(action: {
                self.buttonText = "asdasdads"
            }, label: {
                Text(buttonText)
                     .animation(.linear(duration: 5))
            })
        })
    }
}
```

**Comment by vanities** [comment]
That makes sense, I'm working with a lot of cascading **explicit** animations though

**Comment by fermoya** [comment]
@vanities if you don't have an _infinite pager_ (`loopPages`) I can give have ready a fix soon. Otherwise, it's gonna take me more time. I have that there because when I loop pages to give a carrousel effect the animation makes the items pop into screen with a fade in animation (the items get resorted). That's the only reason that's there. I've seen some answers there to deal with that but I'd like to dig into them before releasing anything

**Comment by vanities** [comment]
Oh dope, thanks for explaining the reasoning for it. I'm not using an infinite pager so I ended up taking the off in a branch

```
 .animation(nil) 
```

and using it. I have seen adding the ID thing works on the first link. Seems to be redrawing on appear like you said when they get resorted.

 Thanks!

**Comment by fermoya** [comment]
the ID workaround doesn't work as expected (it directly removes the animation when dragging). For now, I will have a workaround to remove that line only if `Pager` doesn't have `loopPages` enabled. There's no other way I can think of for now to avoid the elements being reordered for this kind of `Pager` so users will need to use implicit animations for now.

**Comment by fermoya** [comment]
version `1.12.0-beta.1` fixes this issue for infinite pagers as well

**Comment by vanities** [comment]
thank you!
