### ISSUE TITLE
[BUG] Vertical Pager inside ScrollView doesn't receive touches.

### ISSUE THREAD

**Issue by lincolnAB** [fermoya/SwiftUIPager#137]
Hello!
At first let me thank you for this package (it's really awesome!). However is there a way to make vertical Pager work inside ScrollView? I'm trying to achieve similar effect to iOS 14 Stack Widgets Control. I've tried to change gesture priority, but sadly it didn't help. Maybe I'm doing something wrong. Thank you in advance!

**Comment by fermoya** [comment]
Hi @lincolnAB , thanks for your feedback, I appreciate it.

The issue here is you have two verticals scrolls: `Pager` and `ScrollView` so which one should receive the touches? One of them needs to block each other. By default, `Pager` delaysTouches` so that it can be embedded in a `ScrollView` (see [`EmbeddedExampleView.swift`](https://github.com/fermoya/SwiftUIPager/blob/master/Example/SwiftUIPagerExample/Examples/EmbeddedExampleView.swift)). So by default, `Pager` lets `ScrollView` receive the touch and determine if it should receive it or not. I guess this last bit is done in a lower level, because as far as I'm concerned gestures can't fail the way you can do in `UIKit`.

So your only option is to use `delaysTouches(false)` along with `swipeableArea(.allAvailable)`. This will make `Pager` retain the drag and not propagate it. Understand that you won't be able to scroll along the screen if the touch starts on `Pager`

**Comment by lincolnAB** [comment]
Thank you a lot for your time and explanation. Now I see the case
