### ISSUE TITLE
[BUG] Issue with dynamic content

### ISSUE THREAD

**Issue by metsfan** [fermoya/SwiftUIPager#141]
**Describe the bug**
I am trying to load dynamic content from the network when the pager reaches the end. The data is added to the array properly, but the pager behaves very strangely. 

**To Reproduce**
- Add some data to your pager via a @Published or @State array
- When you reach the end of your pager, add more content to the array

**Expected behavior**
You will see that the pager no longer functions correctly. 

**Screenshots / Videos**
I can't show a screenshot or video because of NDA restrictions, but the best I can describe the behavior is that the views appear to "stack" on top, as opposed to scrolling. It's very strange, its best to test for yourself. 

**Environment:**
 -  iOS 14
 - iPhone 7

**Comment by fermoya** [comment]
Hi @metsfan , a sample project  is enough. The description of the bug is very vague and it could be dependant on your implementation. I'm gonna need a sample project here, even dummy code that reproduces the issue. Otherwise, I'm in the dark here and will eventually close the issue if no further information.

I can point you to an example I created for an article in Medium where I use a @Published to dynamically add more items to `Pager`, it works like a charm:
* https://github.com/fermoya/SwiftUIPagerTutorial
* https://medium.com/better-programming/paged-scroll-in-swiftui-a-step-ahead-c6a5f74f9924

Please take a look at this code and see if it can help.

**Comment by fermoya** [comment]
Closing this issue as no more info has been provided. If any questions, feel free to reopen.

To see an implementation using `@Published`, please visit:
* https://github.com/fermoya/SwiftUIPagerTutorial
* https://medium.com/better-programming/paged-scroll-in-swiftui-a-step-ahead-c6a5f74f9924

**Comment by metsfan** [comment]
Thanks for responding. I finally came back to this issue to resolve it and I found that the issue was stemmed from the fact that i was using `\.self` as my key for the pager. Even though my object conformed to `Hashable` and `Equatable` for some reason it did not work right. I changed to using the index of the item which is an integer, and everything works 100% properly now. Thanks for the question response. I have no idea if it's the Pager or my object that has the issue but it doesn't much matter because it works now :) thanks again.
