### ISSUE TITLE
[BUG] Tapping on secondary page list item not working

### ISSUE THREAD

**Issue by javiermorgaz** [fermoya/SwiftUIPager#177]
Hi @fermoya,

I am using your great Pager in my app and I am dealing with something strange:

Adding a couple of pages to the Pager,  both with a list with tappable items, the first time Pager is loaded, in my case is displaying the first page, you can interact with the list items and the onTapGesture is working fine.
The problem is when you scroll to the second page and try to touch one of the items in the second list and the tap gesture is not working. Only when you interact with te scroll list, make the items tappable.
After that both pages are working properly.

Here is a simple code to test the two page views

```
    struct FooView: View {

        var body: some View {

            List {
                ForEach(0..<5, id: \.self) { index in
                    Text("Test")
                        .contentShape(Rectangle())
                        .onTapGesture {
                            print("Tapped")
                        }
                }
            }
            .buttonStyle(PlainButtonStyle())
        }
    }

```
I am using 1.14.2-beta2 running on iOS 13.7 and 14.2 devices/simulators.

Thanks!

**Comment by fermoya** [comment]
Hi @javiermorgaz , I know form my experience `List` bring trouble when wrapped into other views. If I change your `FooView` and use `VStack` instead (give the spacing you need) it works fine.

I'd say there might be an issue with `List`, I know there are some hacks that people use.

I'm not sure I can help much here... I'll keep this opened anyway

**Comment by fermoyadrop** [comment]
@javiermorgaz I found a workaround. 

First of all, make sure you add `edgesIgnoringSafeArea(.all)` to `Pager`. This is the default `List` behaviour so you'll need to use it on `Pager` as you're using it as a `List` container.

Second of all, notice how if you go to the second page and scroll down the `List` making it bounce, the `onTapGesture` works fine. This is because `List` gets redrawn.

Force it to re-render by applying some animation. For instance, easies solution here is to apply `Pager` built in modifier `interactive(_:)`:

```swift
struct FooView: View {

  var body: some View {
    List {
      ForEach(0..<5, id: \.self) { index in
        Text("Test")
          .contentShape(Rectangle())
          .onTapGesture {
            print("Tapped \(index)")
          }
      }
    }
    .buttonStyle(PlainButtonStyle())
  }

}

struct ContentView: View {
  
  @StateObject var page: Page = .first()
  
  var body: some View {
    Pager(page: page, data: Array(1...5), id: \.self) { _ in
      FooView()
    }
    .interactive(0.999)  // force it to re-render
    .edgesIgnoringSafeArea(.all)  // This is `List` default behavior
  }

}
```

**Comment by fermoya** [comment]
@javiermorgaz I found a workaround. 

First of all, make sure you add `edgesIgnoringSafeArea(.all)` to `Pager`. This is the default `List` behavior so you'll need to use it on `Pager` as you're using it as a `List` container.

Second of all, notice how if you go to the second page and scroll down the `List` making it bounce, the `onTapGesture` works fine. This is because `List` gets redrawn.

Force it to re-render by applying some animation. For instance, easies solution here is to apply `Pager` built in modifier `interactive(_:)`:

```swift
struct FooView: View {

  var body: some View {
    List {
      ForEach(0..<5, id: \.self) { index in
        Text("Test")
          .contentShape(Rectangle())
          .onTapGesture {
            print("Tapped \(index)")
          }
      }
    }
    .buttonStyle(PlainButtonStyle())
  }

}

struct ContentView: View {
  
  @StateObject var page: Page = .first()
  
  var body: some View {
    Pager(page: page, data: Array(1...5), id: \.self) { _ in
      FooView()
    }
    .interactive(0.999)  // force it to re-render
    .edgesIgnoringSafeArea(.all)  // This is `List` default behavior
  }

}
```
