### ISSUE TITLE
Sensitivity is extremely low. 

### ISSUE THREAD

**Issue by DandyLyons** [fermoya/SwiftUIPager#185]
Wonderful package. Thank you so much for creating this. 

The default sensitivity is extremely low, even when I use `.sensitivity(.high)`. Thankfully, you added a .custom value, so I used `.sensitivity(.custom(0.001))` and it feels a lot better. (I'm using the sensitivity of Apple's paged views in Podcast, and App Store, and the Home Screen as a reference for how sensitive it should feel.)

Without that custom value, I had to drag almost completely across the screen before it registered as a swipe to the next page. 

(I'm testing on a iPhone SE 2nd Gen, in case that's important info for you.)

**Comment by fermoya** [comment]
@DandyLyons what's the library  version? Also what's the size of your items? The sensitivity feels very different depending on the item size.

Can you please share some code here?

**Comment by DandyLyons** [comment]
I'm on the latest. 2.0.0

That makes sense, that it would feel different depending on the size. 

I've adjusted values including the item size and the sensitivity feels better now. I only raised an issue because I also felt low sensitivity on some of the pagers in the SwiftUIPagerExample app ("right to left, interactive", "Appending on the fly" and "Looping Pager").

**Comment by DandyLyons** [comment]
Thank you for your help.

**Comment by fermoya** [comment]
@DandyLyons the translation is normalized which means you need to swipe from side to side in the container to shift a page completely. This works perfectly for pages that take up most of the container, but not so well when they start shrinking and more pages are visible at the same time. That's why I introduced `sensitivity(_:)`. When items are very small compared to the container, it's better to use `multiplePagination()`.

Thanks for your feedback

**Comment by DandyLyons** [comment]
Oh I see now. I was using sensitivity(_:) but I wasn't using multiplePagination() for those uses.
