### ISSUE TITLE
[QUESTION] Content Loading Policy(?)

### ISSUE THREAD

**Issue by skegget** [fermoya/SwiftUIPager#186]
Hi,

I'm using the pager to be able to swipe between weeks in the current year which means that I'm generating 52-53 views. I have set the recycling ratio to 2 which seems to be good enough for me. If I understand it correctly, my start view plus the previous and next view is loaded upon start, and then views are recycled once I start swiping.

However, I have a problem that I really can't seem to solve. Besides swiping between views, the user can jump to a specific week directly, e.g from week 5 to week 52. If I do this a couple of times, slow swiping gestures becomes a bit jerky. I don't know if this has anything to do with Pager or the recycling ratio at all. It might as well be bad coding from my part since I'm fairly new to this.

So what I'm wondering is how the recycling works if I do these big leaps between views? I'm getting the feeling that I have too many views loaded at the same time which makes the app slow. Once I kill and restart the app everything is smooth again.

To give you a bit o context, every view contains a List{} which in turn contains a ForEach which populates the list.

Many thanks!

**Comment by fermoya** [comment]
Hi @skegget,to do what you suggest you'd need to use a `contentLoadingPolicy(.eager)` which means all items are loaded in memory. A recycling ratio of 2 means that just enough elements to fill 2 times the container (`Pager` total space) will be loaded. If you need to jump from one page to another and skip a bunch of items in between, all items should be loaded to achieve the desired effect of scrolling through all the items.

See [ColorsExampleView.Swift](https://github.com/fermoya/SwiftUIPager/blob/develop/Example/SwiftUIPagerExample/Examples/ColorsExampleView.swift) to see how it works.

**Comment by skegget** [comment]
Thanks for the quick response! 

Hm OK. I have actually tested `contentLoadingPolicy(.eager)`. The weird part is that the jerky feeling then appears immediately when the app is started. Another performance suspect is the combination of List{} and ForEach{}. Have you ever tried  anything similar within Pager?

**Comment by fermoya** [comment]
@skegget tried having a `List` as a page? In my experience, it brings trouble as for `List` nature.

Can you please share some code and a video? 

> the jerky feeling then appears immediately when the app is started

I'm not sure I follow. Please, always try to come up with a simple sample code (a page that's just a `Text`, for instance) and a simple scenario (just a `StateObject` page). If the issue is reproduced, then simply bring the sample code here and I'll give it a look. Then start building up from there, most of the times the it's a State Management issue in the App code and not a problem with the library. 

You can also try reproducing the issue in the example I mentioned in my previous comment.

**Comment by skegget** [comment]
Great, will do that and get back to you!

Thanks!

**Comment by skegget** [comment]
OK, so I've simplified my case a lot but I'm still able to reproduce the problem. Actually, for some reason this example is even slower than my original case.

```
import SwiftUI
import SwiftUIPager

struct ContentView: View {
    @StateObject var page: Page = .first()
    var items = Array(1..<53)
    
    var body: some View {
        Pager(page: page,
              data: items,
              id: \.self) {
            self.pageView($0)
        }.contentLoadingPolicy(.eager)
    }
    
    func pageView(_ page: Int) -> some View {
        VStack {
            Text("\(page)")
            List {
                ForEach(1..<11, id: \.self) { value in
                    Text("Hello \(value)")
                }
            }
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
```

**Comment by fermoya** [comment]
@skegget I see it now, thanks for sharing. 

As I mentioned, I know from experience that `List` doesn't work as well as it should with `Pager`. I'm not sure why but my guess is the way it's built internally (it's not a `SwiftUI` native view but a wrapper of `UITableView`). Actually if you comment the `List` part and you leave the rest (`ForEach` and `Text`) you'll notice it works fine and the scroll isn't "jerky" as you mentioned.

So your issue is you're loading 54 pages that contain a `List`. `List` are expensive views in terms of resources and using `Pager` in `eager` mode with a `List` isn't realistic.

As an alternative, I'd suggest using `ScrollView` and `LazyVStack` instead. Try this out (and notice I've incremented `ForEach` to iterate 100 times which makes it event a worse case than before):
```swift
struct ContentView: View {
    @StateObject var page: Page = .first()
    var items = Array(1..<53)

    var body: some View {
        Pager(page: page,
              data: items,
              id: \.self) {
            self.pageView($0)
        }
        .contentLoadingPolicy(.eager)
    }

    func pageView(_ page: Int) -> some View {
        VStack {
            Text("\(page)")
            ScrollView {
                LazyVStack(alignment: .leading) {
                    ForEach(1..<100, id: \.self) { value in
                        Text("Hello \(value)")
                            .frame(height: 50)
                    }
                }
                .contentShape(Rectangle())
            }
        }
    }
}
```
