### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Archetapp** [fermoya/SwiftUIPager#203]
**Describe the bug**
Animations are inconsistent when scrolling. Sometimes they easeOut, sometimes they just jump.

**To Reproduce**
```
return Pager(page: self.currentPage, data: self.homeProductsObject.discoverProducts, id: \.id, content: {
            product in
            ProductCell(rootIsActive : self.$rootIsActive, product: product)
// Switching this out with any other view yields the same result.
        })
        .vertical()
        .interactive(scale: 1.0)
```
**Expected behavior**
We have a view that fills the entire screen to which we scroll up and down. Imagine Tik Tok. In the previous version we were using, 1.4.3, we noticed the animations were very laggy, so we saw that this issue was fixed in 2.1.0. So I updated, and yes the dragging is way close to a 1:1 feel... the animations can be very choppy at times.

**Screenshots / Videos**
https://user-images.githubusercontent.com/8635253/110881622-e47ff700-829d-11eb-9b2b-4e5d40fd8f2b.mov

**Environment:**
 - OSX: iOS
 - Device iPhone 11
- SwiftUIPager version : 2.1.0

**Comment by fermoya** [comment]
@Archetapp can you try `2.0.0` and let me know if you experience the same jumps, please?

**Comment by Archetapp** [comment]
Looks like that yes it'd fixed the issue in terms of it bugging out... but the animation has reverted back to being laggy. I'm looking at the source files now and it looks like onDragChanged in PagerContent.swift we're using a default animation... maybe if we set that to a custom animation with a faster speed?

**Comment by fermoya** [comment]
@Archetapp when you say "laggy", do you mean it slows down the drag and the item doesn't seem to move exactly at the same time as the finger (1:1 dragging someone called it)?

It might be a matter of trying a different animation or tweaking the linear animation, in case you want to give it a shot.

### Context
At first that piece executed a simple `withAnimation { ... }` (thats version `2.0.0` and older). It was proposed to delete the `withAnimation` and just leave the block but that caused problems (that was `2.0.2` and the effect was similar to the one in your video but even more obvious). I changed it to `withAnimation(.linear(0.1)`. A shorter animation would mean a a closer experience to this 1:1 effect. Also, linear so that it feels more natural.

**Comment by Archetapp** [comment]
Yes, that's exactly what I meant with laggy. And so does version 2.1.0 have that change `withAnimation(.linear(0.1))`?

I might fork SwiftUIPager to see if I can play around with any of the variables to get closer to the experience I need.

**Comment by fermoya** [comment]
@Archetapp yes that's how it is currently in `2.1.0`: `withAnimation(.linear(0.1))`. I've changed it to `withAnimation(.linear(0.2))` and it's more difficult to reproduce but it still happens. I'd say it's a matter of finding the right compromise. 

In any case, the default animation I think it's `easeInOut`. `linear` will look better

**Comment by fermoya** [comment]
Is this solved @Archetapp ?

**Comment by fermoya** [comment]
I saw you forked the repo and changed the duration to `0.4`. Can you show me how does it look like that please?

https://github.com/Archetapp/SwiftUIPager/commit/eedcd5c4590086f6255b47b616e121802d410f6d

**Comment by Archetapp** [comment]
Hey! Okay, so in the end, I put in an interactiveSpring to which you can change the response and what not. It seems to work well for my use case... the only issue is, sometimes it switches between the dragChanged animation or the dragEnded animation. So, at the moment, I made them both the same.

The results looks pretty good.

https://user-images.githubusercontent.com/8635253/111223017-311b4900-85a2-11eb-9a1a-7a73751987dc.mov

**Comment by fermoya** [comment]
Thanks @Archetapp . Can I ask why didn't you decide to use the default values `.interactiveSpring()`? I'm seeing the default `response` is 0.15 and you're using 0.3. The default implementation should be faster.

I'm asking this because I'm planning to change it. According to the [documentation](https://developer.apple.com/documentation/swiftui/animation/interactivespring(response:dampingfraction:blendduration:)) it is _intended for driving interactive animations_. I'd be replacing `.linear(0.1)` with `.interactiveSpring()` while dragging. Then you could simple use `pagingAnimation(_:)` to whatever animation you prefer (in your case, `.interactiveSpring(response: 0.3, dampingFraction: 0.8, blendDuration: 0.5)`)

**Comment by Archetapp** [comment]
So, I went with 0.3 because while yes, it's a tad slower response time while dragging... sometimes (I'm not sure why) the animation gets applied even when I have stopped scrolling, and creates a jumpy effect. So, what I did was more or less a compromise so that it works for my app well enough. (Not too laggy, but not too jumpy if for some reason the dragEnded animation never gets called).
