### ISSUE TITLE
[BUG] Event driven navigation in looping Pager

### ISSUE THREAD

**Issue by louis1001** [fermoya/SwiftUIPager#234]
**Describe the bug**
When using a looping `Pager`, updating the Page element with `.update(.next)` works as intended until the last page, and then stops.

**To Reproduce**
```swift
import SwiftUI
import SwiftUIPager

struct SampleView: View {
    @ObservedObject var page1 = Page.first()
    var data = Array(0..<5)
    var body: some View {
        Pager(page: page1, data: data, id: \.self) { element in
            Text("\(element)")
                .frame(width: 300, height: 300)
                .background(Color.gray)
        }
        .onAppear {
            Timer.scheduledTimer(withTimeInterval: 2, repeats: true) {_ in
                withAnimation {
                    page1.update(.next)
                }
            }
        }
    }
}
```

**Expected behavior**
When it gets to the last page, I expect it to animate going the next page (the first one), like it would with user input. 

**Environment:**
 - OS: iOS 14.7.1 (with support for 13.6)
 - Device:  iPhone SE 2020
- SwiftUIPager version: 2.3.1

**Comment by fermoya** [comment]
@louis1001 thanks for reporting. This should be easy to fix, I'll see if I can get some time for that.

The issue is [here](https://github.com/fermoya/SwiftUIPager/blob/168614398b1986a6e07060d5d127122643cfe724/Sources/SwiftUIPager/Page.swift#L28) in case you wanted to raise a PR yourself. `Page` needs to know `Pager` is looping so that it returns the right index. 

It might be more complicated than that but that's a start

**Comment by louis1001** [comment]
Thanks!
I'll take a look at it.

My first impulse is to give `Page` a `Pager?` that it could check.
