### ISSUE TITLE
Every page is initialized at the same time

### ISSUE THREAD

**Issue by carlosrc** [fermoya/SwiftUIPager#26]
I want to know if there is some way to load on demand each page. Now is calling onAppear method in each page at once.

Also the init method on each view is called multiple times on change active page. Maybe it could be a performance problem with heavy operations. Is there any way to solve it?

Tthanks for the help.

**Comment by fermoya** [comment]
Hi @carlosrc ,

Currently `Pager` initializes the current page and some more hidden pages to assure a smooth scroll. That is, right now the recycling ratio is 5 which means it assures there are enough pages to fill the screen twice on each side of the scroll. This doesn't mean it initializes all pages at once, just the ones it needs. For instance, in the [example project](https://github.com/fermoya/SwiftUIPager/tree/master/Example), first tab, `Pager` keeps in memory a maximum of 5 pages at once, based on the page size.

Regarding the init method, `Pager` needs to reload as many times as SwiftUI needs to repaint the page. That is, if you're dragging a page to swipe sideways, you should expect multiple calls to the initializer. This doesn't mean the page is recreated, but it is refreshed. Any Binding, State or EnvironmentObject variable triggers a view refresh. `Pager` holds a `draggingOffset` state to update the page offset and that's why you might see the init method gets called so often

**Comment by carlosrc** [comment]
Thanks for your help, @fermoya. I'm new on SwiftUI and I'm a little bit confused about the life cycle. 

So, is there a way to detect an event when the active page is changed?

And another question... (sorry for the mix), I'm using MVVM, and my viewModel is initialized when the view initializes. I think this provokes an unlink between view and viewModel. When I update a property in the viewModel, doesn't refresh in the view. Any ideas about this?

Thanks.

**Comment by fermoya** [comment]
No problem. 

For the first part, `Pager` has an event `onPageChanged` that will tell you when the page is changed. 

For the second part, you need to make your ViewModel publish the changed. That is, it needs to implement `ObservableObject` and mark some properties as `@Published`. Then, inside your view you should declare a wrapped value `@ObservedObject`:

```
class ViewModel: ObservableObject {
    @Published var field: String = "Some value"
}

struct MyView: View {

    @ObservedObject var viewModel: ViewModel

    var body: some View {
        EmptyView()
    }
}
```
