### ISSUE TITLE
Can't seem to embed into a NavigationView

### ISSUE THREAD

**Issue by parisman** [fermoya/SwiftUIPager#28]
Wonderful job on this. Answered my prayers... almost. But, I need to embed it in a NavigationView... which does not seem to work...

**Comment by fermoya** [comment]
Hi @parisman ,

What's your issue exactly? I have several examples [here](https://github.com/fermoya/SwiftUIPager/tree/master/Example) and in all of them I use a `NavigationView`, have you checked them?

**Comment by parisman** [comment]
Fernando,

Thanks for the outreach. The issue is that I want to put your view inside of a NavigationView, not the other way around...

Cheers,

Lee

Sent via iPhone.

**Comment by fermoya** [comment]
Hi @parisman ,

I think you mean embed `NavigationView` inside `Pager` which is not possible. `NavigationView` is designed to be the top most view in the view hierarchy. If you want to change the title or the navbar buttons depending on the page, you can do something like:
```
@State var page = 0

var body: some View {
     NavigationView {
         Pager(page: $page, ...)
               .navigationBarTitle(title(forPage: page))
     }
}

func title(forPage page: Int) {
     return page % 2 == 0 ? "Even" : "Odd"
}
```

The examples that I shared with you embed a `Pager` into a `NavigationView`. The other way round as I said isn't possible.

Cheers

**Comment by wuyb** [comment]
Hi @fermoya ,

I think I may know what @parisman means, as I have the same question.

The example in your project is using plain values (Int) as the data. I am using a struct, received from server side. For each struct instance, a custom view is displayed. In that custom view, there is a NavigationLink linking to a detail view.

When I tap on the NavigationLink, it goes to the detail view but pops out immediately. This might have the same root cause as https://stackoverflow.com/questions/58302913/swiftui-navigationlink-pops-immediately-if-used-within-foreach/58305884#58305884

However in my code, data are always in the view model. By observation, it seems the redraw happens on the Pager. Would it be possible that the Pager itself triggers it for change of GeometryReader?

Thanks

**Comment by fermoya** [comment]
Hi @wuyb , can you share some code, please? What version are you using? The `GeometryReader` should affect `Pager` once, `onAppear`
