### ISSUE TITLE
Negative Index

### ISSUE THREAD

**Issue by JetPlaneJJ** [fermoya/SwiftUIPager#87]
**Describe the bug**
Pager seems to support negative pages? When I insert my content into the vertical scrolling pager, it seems that I am able to scroll up from index 0 to index -1. I am wondering how to get rid of this.

**To Reproduce**

1. Pager appears and starts at index 0 as expected. All expected content is viewable and user can swipe through all of the positive index pages normally.
2. However, at index 0, if the user swipes up, the index becomes -1 and they are unable to see any content. 
3. After that, the user might swipe up again, and the index returns to 0. 
4. The user could also swipe back down from index -1 to return to index 0.

- Sample code: This is what I am currently using.
`
Pager(page: self.$currentPage, data: Array(0..<self.postArray.count),
                          id: \.self, content: { index in
                            PostView(
                                loading: self.$loading,
                                postIndex: index,
                                receivedIndex: self.$currentPage)
                    }) // pager
                        .contentLoadingPolicy(.lazy(recyclingRatio: 2)) // to help with lag
                        .vertical()
                        .swipeInteractionArea(.page) // or else the post carousel can't be scrolled
                        .onPageChanged { newIndex in
                            self.currentPage = newIndex
                    } // page change
`

**Expected behavior**
Pager shouldn't have negative indices or an index -1. Or at least the option to disable such feature?

**Environment:**
 - OSX: iOS 13.6
 - Device: iPhone X
-  SwiftUIPager version: 1.9.0.beta-3, I know it is not the most updated version, but I did not update to that new version (production release 1.9.0) because it caused new issues in the scrolling experience (hard to scroll, laggy videos).

**Comment by JetPlaneJJ** [comment]
Apologies, I found a workaround:

`.onPageChanged { newIndex in
                        ... self.currentPage = newIndex < 0 ? 0 : newIndex 
                    } `

**Comment by fermoya** [comment]
Hi @JetPlaneJJ , this is a indeed a bug and has been fixed in version [1.9.2](https://github.com/fermoya/SwiftUIPager/releases/tag/1.9.2). Some notes here for your code:
* If you don't need `.onPageChanged { newIndex in self.currentPage = newIndex }`. You're passing a binding to `Pager` which means that variable is shared by your `ContentView` and `Pager`. It gets updated automatically.
* The scroll was lagged in version 1.9.0 but was fixed in version 1.9.1.
* `.swipeInteractionArea(.page)` is the default behavior of `Pager`, so that doesn't fix anything

Please don't be afraid to open any issue if you encounter problems.
